{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "keAece_Vs2g2",
        "outputId": "d15df716-8527-47ff-85c3-3ac94e819746"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "K-Fold Cross Validation\n",
            "\n",
            "Fold 1\n",
            "Train indices: [4 5 6 7]\n",
            "Test indices : [0 1 2 3]\n",
            "Accuracy : 0.25\n",
            "\n",
            "Fold 2\n",
            "Train indices: [0 1 2 3]\n",
            "Test indices : [4 5 6 7]\n",
            "Accuracy : 0.75\n",
            "\n",
            "Stratified K-Fold Cross Validation\n",
            "\n",
            "Fold 1\n",
            "Train indices: [2 5 6 7]\n",
            "Test indices : [0 1 3 4]\n",
            "Accuracy : 0.5\n",
            "\n",
            "Fold 2\n",
            "Train indices: [0 1 3 4]\n",
            "Test indices : [2 5 6 7]\n",
            "Accuracy : 0.5\n",
            "\n",
            "Leave-One-Out Cross Validation\n",
            "\n",
            "Iteration 1\n",
            "Train indices: [1 2 3 4 5 6 7]\n",
            "Test index : [0]\n",
            "Accuracy : 1.0\n",
            "\n",
            "Iteration 2\n",
            "Train indices: [0 2 3 4 5 6 7]\n",
            "Test index : [1]\n",
            "Accuracy : 1.0\n",
            "\n",
            "Iteration 3\n",
            "Train indices: [0 1 3 4 5 6 7]\n",
            "Test index : [2]\n",
            "Accuracy : 1.0\n",
            "\n",
            "Iteration 4\n",
            "Train indices: [0 1 2 4 5 6 7]\n",
            "Test index : [3]\n",
            "Accuracy : 0.0\n",
            "\n",
            "Iteration 5\n",
            "Train indices: [0 1 2 3 5 6 7]\n",
            "Test index : [4]\n",
            "Accuracy : 0.0\n",
            "\n",
            "Iteration 6\n",
            "Train indices: [0 1 2 3 4 6 7]\n",
            "Test index : [5]\n",
            "Accuracy : 1.0\n",
            "\n",
            "Iteration 7\n",
            "Train indices: [0 1 2 3 4 5 7]\n",
            "Test index : [6]\n",
            "Accuracy : 0.0\n",
            "\n",
            "Iteration 8\n",
            "Train indices: [0 1 2 3 4 5 6]\n",
            "Test index : [7]\n",
            "Accuracy : 1.0\n"
          ]
        }
      ],
      "source": [
        "import numpy as np\n",
        "from sklearn.model_selection import KFold, StratifiedKFold, LeaveOneOut\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.metrics import accuracy_score\n",
        "# Larger and more balanced sample dataset\n",
        "X = np.array([[1,2], [2,3], [3,4], [4,5], [5,6], [6,7], [7,8], [8,9]])\n",
        "y = np.array([0, 0, 0, 1, 1, 1, 0, 1])\n",
        "model = LogisticRegression()\n",
        "# ------------------ K-Fold Cross Validation ------------------\n",
        "print(\"K-Fold Cross Validation\")\n",
        "kf = KFold(n_splits=2)\n",
        "for fold, (train_index, test_index) in enumerate(kf.split(X), start=1):\n",
        "    X_train, X_test = X[train_index], X[test_index]\n",
        "    y_train, y_test = y[train_index], y[test_index]\n",
        "    model.fit(X_train, y_train)\n",
        "    y_pred = model.predict(X_test)\n",
        "    acc = accuracy_score(y_test, y_pred)\n",
        "    print(f\"\\nFold {fold}\")\n",
        "    print(\"Train indices:\", train_index)\n",
        "    print(\"Test indices :\", test_index)\n",
        "    print(\"Accuracy :\", acc)\n",
        "# ------------------ Stratified K-Fold ------------------\n",
        "print(\"\\nStratified K-Fold Cross Validation\")\n",
        "skf = StratifiedKFold(n_splits=2)\n",
        "for fold, (train_index, test_index) in enumerate(skf.split(X, y),\n",
        "                                                start=1):\n",
        "    X_train, X_test = X[train_index], X[test_index]\n",
        "    y_train, y_test = y[train_index], y[test_index]\n",
        "    model.fit(X_train, y_train)\n",
        "    y_pred = model.predict(X_test)\n",
        "    acc = accuracy_score(y_test, y_pred)\n",
        "    print(f\"\\nFold {fold}\")\n",
        "    print(\"Train indices:\", train_index)\n",
        "    print(\"Test indices :\", test_index)\n",
        "    print(\"Accuracy :\", acc)\n",
        "# ------------------ Leave-One-Out ------------------\n",
        "print(\"\\nLeave-One-Out Cross Validation\")\n",
        "loo = LeaveOneOut()\n",
        "for i, (train_index, test_index) in enumerate(loo.split(X), start=1):\n",
        "    X_train, X_test = X[train_index], X[test_index]\n",
        "    y_train, y_test = y[train_index], y[test_index]\n",
        "    model.fit(X_train, y_train)\n",
        "    y_pred = model.predict(X_test)\n",
        "    acc = accuracy_score(y_test, y_pred)\n",
        "    print(f\"\\nIteration {i}\")\n",
        "    print(\"Train indices:\", train_index)\n",
        "    print(\"Test index :\", test_index)\n",
        "    print(\"Accuracy :\", acc)"
      ]
    }
  ]
}